Repository trueplan/forecast, pull requests merged in 2022-06, with the labels that each got.

#102 chore: update gh actions with lint and asana flows
  .github/workflows/asana_attachment.yml
  .github/workflows/asana_move_to_complete.yml
  .github/workflows/asana_move_to_review.yml
  .github/workflows/pull_request.yml
  cspell.json
  pull_request_template.md
Labels: chore

#107 chore: wrap Drag and Drop File component in forwardRef
  .changeset/shaggy-teachers-lie.md
  packages/components/src/components/drag-and-drop-file-container/src/index.tsx
Labels: bug

#112 feat: create basic table component
  .changeset/cyan-shoes-agree.md
  cspell.json
  packages/components/src/components/table/__tests__/table.test.tsx
  packages/components/src/components/table/index.ts
  packages/components/src/components/table/src/TBody.tsx
  packages/components/src/components/table/src/TD.tsx
  packages/components/src/components/table/src/TH.tsx
  packages/components/src/components/table/src/THead.tsx
  packages/components/src/components/table/src/TR.tsx
  packages/components/src/components/table/src/Table.tsx
  packages/components/src/components/table/src/index.tsx
  packages/components/src/components/table/src/styles.ts
  packages/components/src/components/table/stories/index.stories.tsx
  packages/components/src/index.ts
Labels: feature

#114 fix(components): added pointer event none to select chevron icon
  .changeset/silver-geckos-invite.md
  packages/components/src/components/select/src/Select.tsx
Labels: bug

#116 Feat/add loading illustration
  .changeset/swift-kids-join.md
  packages/components/src/components/drag-and-drop-file-container/src/index.tsx
  packages/components/src/components/drag-and-drop-file-container/stories/index.stories.tsx
Labels: feature

#119 fix: drag and drop file container losing hover when dragging over image or button
  .changeset/poor-clocks-laugh.md
  packages/components/src/components/drag-and-drop-file-container/src/styles.ts
  packages/components/src/components/drag-and-drop-file-container/stories/index.stories.tsx
Labels: bug

#121 chore(icons): add archive, unarchive, merge, unmerge icons
  .changeset/cold-bats-count.md
  cspell.json
  packages/icons/index.ts
  packages/icons/json/icons.json
  packages/icons/src/ArchiveIcon.tsx
  packages/icons/src/MergeIcon.tsx
  packages/icons/src/UnarchiveIcon.tsx
  packages/icons/src/UnmergeIcon.tsx
  packages/icons/svg/archive.svg
  packages/icons/svg/merge.svg
  packages/icons/svg/unarchive.svg
  packages/icons/svg/unmerge.svg
Labels: chore

#124 feat: row and col span for TD and TH
  .changeset/clean-socks-protect.md
  packages/components/src/components/table/src/TD.tsx
  packages/components/src/components/table/src/TH.tsx
Labels: chore

#125 fix: remove yarn install from changeset
  .github/workflows/main.yml
Labels: bug

#126 feat(components): add prop that controls visibility of toggle label text
  .changeset/loud-beans-pay.md
  packages/components/src/components/drawer/stories/index.stories.tsx
  packages/components/src/components/toggle/src/index.tsx
  packages/components/src/components/toggle/src/types.ts
  packages/components/src/components/toggle/stories/index.stories.tsx
Labels: feature

#128 fix: specify table font stylings
  .changeset/five-months-remember.md
  packages/components/src/components/table/src/styles.ts
Labels: bug

#135 chore(components): add alert doc storybook page
  .changeset/big-insects-join.md
  .changeset/serious-houses-taste.md
  packages/components/src/components/alert/src/Alert.tsx
  packages/components/src/components/alert/src/types.ts
  packages/components/src/components/alert/stories/alert.stories.tsx
Labels: chore

#136 fix: fix package json version for changesets
  .changeset/khaki-gifts-guess.md
  packages/components/package.json
  packages/icons/package.json
  yarn.lock
Labels: bug

#138 chore(components): storybook docs for avatar, badge, button, card
  .changeset/plenty-drinks-cross.md
  packages/components/src/components/avatar/src/Avatar.tsx
  packages/components/src/components/avatar/src/types.ts
  packages/components/src/components/avatar/stories/index.stories.tsx
  packages/components/src/components/badge/src/badge.tsx
  packages/components/src/components/badge/src/types.ts
  packages/components/src/components/badge/stories/badge.stories.tsx
  packages/components/src/components/button/src/Button.tsx
  packages/components/src/components/button/src/types.ts
  packages/components/src/components/button/stories/index.stories.tsx
  packages/components/src/components/card/src/Card.tsx
  packages/components/src/components/card/src/CardFooter.tsx
  packages/components/src/components/card/src/CardHeader.tsx
  packages/components/src/components/card/src/types.ts
  packages/components/src/components/card/stories/index.stories.tsx
Labels: chore
