Repository trueplan/forecast, pull requests merged in 2022-03, with the labels that each got.

#59 feat: use google's inter font
  .changeset/great-scissors-speak.md
  .storybook/preview-head.html
  .storybook/static/fonts/Inter-Medium.ttf
  .storybook/static/fonts/Inter-Regular.ttf
  .storybook/static/fonts/Inter-SemiBold.ttf
  .storybook/static/fonts/Inter.var.woff2
  packages/components/package.json
  packages/components/src/components/anchor/stories/index.stories.tsx
  packages/icons/package.json
  packages/theme/package.json
  packages/theme/src/index.ts
  packages/theme/src/styles/fonts.ts
  packages/theme/src/themes/default/index.ts
  website/components/layout/index.tsx
  website/pages/_app.tsx
  yarn.lock
Labels: feature

#58 chore: set up npm publish infrastructure
  .changeset/config.json
  .github/release-drafter-config.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .pnp.cjs
  .yarn/cache/@changesets-changelog-github-npm-0.4.3-aa0bb1dc0f-4bca5c4f15.zip
  .yarn/cache/@changesets-get-github-info-npm-0.5.0-1ad8cdd598-9867a78753.zip
  .yarn/cache/@changesets-types-npm-4.1.0-c7ed225741-72c1f58044.zip
  .yarn/cache/dataloader-npm-1.4.0-ba03bd2183-e2c93d43af.zip
  .yarn/cache/node-fetch-npm-2.6.7-777aa2a6df-8d816ffd1e.zip
  package.json
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/icons/CHANGELOG.md
  packages/icons/package.json
  packages/theme/CHANELOG.md
  packages/theme/package.json
  yarn.lock
Labels: chore

#61 fix: adjust dev deps in hopes of fixing changeset
  .github/workflows/main.yml
  packages/components/package.json
  packages/icons/package.json
  yarn.lock
Labels: bug

#67 fix: unplug open for cross platform support
  .pnp.cjs
  package.json
  yarn.lock
Labels: bug

#69 fix: change npm dist files and build scripts
  .changeset/wicked-fans-invite.md
  configs/rollup/rollup.config.js
  cspell.json
  packages/components/package.json
  packages/components/src/components/toast/src/index.tsx
  packages/icons/package.json
  packages/theme/package.json
Labels: bug
