Repository trueplan/forecast, pull requests merged in 2022-05, with the labels that each got.

#89 TRUE-999 | New line height values
  .changeset/rude-countries-camp.md
  .changeset/thirty-moose-yawn.md
  packages/components/src/components/avatar/src/Avatar.tsx
  packages/components/src/components/tag/src/styles.ts
  packages/components/src/primitives/text/src/index.tsx
  packages/components/src/primitives/text/src/styles.ts
  packages/theme/src/themes/default/index.ts
Labels: feature

#90 feat(avatar): adds bg color util
  .changeset/cool-emus-notice.md
  packages/components/src/components/avatar/__tests__/avatar.test.tsx
  packages/components/src/components/avatar/src/utils.ts
  packages/components/src/components/avatar/stories/index.stories.tsx
Labels: chore

#94 feat(components): add select-comobobox reusable component
  .changeset/modern-carpets-brush.md
  packages/components/src/components/select-combobox/index.ts
  packages/components/src/components/select-combobox/src/index.tsx
  packages/components/src/components/select-combobox/src/styles.ts
  packages/components/src/components/select-combobox/stories/index.stories.tsx
Labels: feature

#96 fix: radio button alignment in firefox
  .changeset/six-seahorses-sniff.md
  packages/components/src/components/radio-group/src/Radio.tsx
  packages/components/src/components/radio-group/src/styles.ts
Labels: bug
